global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8000']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
